import type { ArchitectureTemplate } from '../types/templates.js';

export const architectureTemplates: ArchitectureTemplate[] = [
  {
    id: 'microservices',
    name: 'Microservices',
    description: 'API Gateway routing to independent services with databases and caching',
    category: 'microservices',
    nodes: [
      { id: 'tpl-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 50 }, config: { rateLimit: 10000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'tpl-auth', type: 'auth-service', category: 'backend', label: 'Auth Service', position: { x: 150, y: 200 }, config: { provider: 'JWT', replicas: 2, sessionTTL: '24h' }, status: 'healthy' },
      { id: 'tpl-api', type: 'api-service', category: 'backend', label: 'API Service', position: { x: 400, y: 200 }, config: { language: 'Node.js', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'tpl-worker', type: 'worker-service', category: 'backend', label: 'Worker Service', position: { x: 650, y: 200 }, config: { language: 'Python', replicas: 2, concurrency: 10 }, status: 'healthy' },
      { id: 'tpl-pg', type: 'postgresql', category: 'database', label: 'PostgreSQL', position: { x: 250, y: 400 }, config: { storage: '100GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'tpl-redis', type: 'redis', category: 'cache', label: 'Redis', position: { x: 500, y: 400 }, config: { memory: '2GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
      { id: 'tpl-kafka', type: 'kafka', category: 'queue', label: 'Kafka', position: { x: 650, y: 400 }, config: { partitions: 6, replicationFactor: 3, retentionPeriod: '7d' }, status: 'healthy' },
    ],
    edges: [
      { id: 'tpl-e1', source: 'tpl-gw', target: 'tpl-auth' },
      { id: 'tpl-e2', source: 'tpl-gw', target: 'tpl-api' },
      { id: 'tpl-e3', source: 'tpl-gw', target: 'tpl-worker' },
      { id: 'tpl-e4', source: 'tpl-api', target: 'tpl-pg' },
      { id: 'tpl-e5', source: 'tpl-api', target: 'tpl-redis' },
      { id: 'tpl-e6', source: 'tpl-worker', target: 'tpl-kafka' },
    ],
  },
  {
    id: 'monolith-queue',
    name: 'Monolith + Queue',
    description: 'Load balanced monolith with async worker processing via message queue',
    category: 'monolith',
    nodes: [
      { id: 'tpl-lb', type: 'load-balancer', category: 'infrastructure', label: 'Load Balancer', position: { x: 400, y: 50 }, config: { algorithm: 'round-robin', healthCheckInterval: 30, maxConnections: 10000 }, status: 'healthy' },
      { id: 'tpl-web', type: 'web-app', category: 'frontend', label: 'Web App', position: { x: 250, y: 200 }, config: { framework: 'Next.js', replicas: 2, cdn: true }, status: 'healthy' },
      { id: 'tpl-api', type: 'api-service', category: 'backend', label: 'API Service', position: { x: 550, y: 200 }, config: { language: 'Node.js', replicas: 3, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'tpl-pg', type: 'postgresql', category: 'database', label: 'PostgreSQL', position: { x: 250, y: 400 }, config: { storage: '100GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'tpl-redis', type: 'redis', category: 'cache', label: 'Redis', position: { x: 550, y: 400 }, config: { memory: '2GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
      { id: 'tpl-rmq', type: 'rabbitmq', category: 'queue', label: 'RabbitMQ', position: { x: 700, y: 300 }, config: { queues: 5, durable: true, maxMessageSize: '1MB' }, status: 'healthy' },
      { id: 'tpl-worker', type: 'worker-service', category: 'backend', label: 'Worker', position: { x: 700, y: 450 }, config: { language: 'Python', replicas: 2, concurrency: 10 }, status: 'healthy' },
    ],
    edges: [
      { id: 'tpl-e1', source: 'tpl-lb', target: 'tpl-web' },
      { id: 'tpl-e2', source: 'tpl-lb', target: 'tpl-api' },
      { id: 'tpl-e3', source: 'tpl-api', target: 'tpl-pg' },
      { id: 'tpl-e4', source: 'tpl-api', target: 'tpl-redis' },
      { id: 'tpl-e5', source: 'tpl-api', target: 'tpl-rmq' },
      { id: 'tpl-e6', source: 'tpl-rmq', target: 'tpl-worker' },
    ],
  },
  {
    id: 'event-driven',
    name: 'Event-Driven',
    description: 'Event-driven architecture with Kafka streaming to multiple consumer services',
    category: 'event-driven',
    nodes: [
      { id: 'tpl-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 50 }, config: { rateLimit: 10000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'tpl-api', type: 'api-service', category: 'backend', label: 'Producer API', position: { x: 400, y: 200 }, config: { language: 'Go', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'tpl-kafka', type: 'kafka', category: 'queue', label: 'Kafka', position: { x: 400, y: 350 }, config: { partitions: 12, replicationFactor: 3, retentionPeriod: '7d' }, status: 'healthy' },
      { id: 'tpl-w1', type: 'worker-service', category: 'backend', label: 'Analytics Worker', position: { x: 150, y: 500 }, config: { language: 'Python', replicas: 3, concurrency: 20 }, status: 'healthy' },
      { id: 'tpl-w2', type: 'worker-service', category: 'backend', label: 'Notification Worker', position: { x: 400, y: 500 }, config: { language: 'Node.js', replicas: 2, concurrency: 10 }, status: 'healthy' },
      { id: 'tpl-w3', type: 'worker-service', category: 'backend', label: 'Search Indexer', position: { x: 650, y: 500 }, config: { language: 'Java', replicas: 2, concurrency: 5 }, status: 'healthy' },
      { id: 'tpl-mongo', type: 'mongodb', category: 'database', label: 'MongoDB', position: { x: 150, y: 650 }, config: { storage: '50GB', replicaSet: true, sharding: false }, status: 'healthy' },
      { id: 'tpl-redis', type: 'redis', category: 'cache', label: 'Redis', position: { x: 650, y: 650 }, config: { memory: '4GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'tpl-e1', source: 'tpl-gw', target: 'tpl-api' },
      { id: 'tpl-e2', source: 'tpl-api', target: 'tpl-kafka' },
      { id: 'tpl-e3', source: 'tpl-kafka', target: 'tpl-w1' },
      { id: 'tpl-e4', source: 'tpl-kafka', target: 'tpl-w2' },
      { id: 'tpl-e5', source: 'tpl-kafka', target: 'tpl-w3' },
      { id: 'tpl-e6', source: 'tpl-w1', target: 'tpl-mongo' },
      { id: 'tpl-e7', source: 'tpl-w3', target: 'tpl-redis' },
    ],
  },
  {
    id: 'serverless',
    name: 'Serverless API',
    description: 'CDN-fronted serverless API with managed database and async processing',
    category: 'serverless',
    nodes: [
      { id: 'tpl-cdn', type: 'cdn', category: 'frontend', label: 'CDN', position: { x: 400, y: 50 }, config: { provider: 'CloudFront', cachePolicy: '24h' }, status: 'healthy' },
      { id: 'tpl-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 200 }, config: { rateLimit: 10000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'tpl-api', type: 'api-service', category: 'backend', label: 'Lambda API', position: { x: 250, y: 350 }, config: { language: 'Node.js', replicas: 1, cpu: '250m', memory: '256MB', autoscaling: true }, status: 'healthy' },
      { id: 'tpl-sqs', type: 'sqs', category: 'queue', label: 'SQS', position: { x: 550, y: 350 }, config: { type: 'Standard', visibilityTimeout: 30, retentionPeriod: '4d' }, status: 'healthy' },
      { id: 'tpl-worker', type: 'worker-service', category: 'backend', label: 'Lambda Worker', position: { x: 550, y: 500 }, config: { language: 'Python', replicas: 1, concurrency: 5 }, status: 'healthy' },
      { id: 'tpl-pg', type: 'postgresql', category: 'database', label: 'RDS PostgreSQL', position: { x: 250, y: 500 }, config: { storage: '50GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'tpl-redis', type: 'redis', category: 'cache', label: 'ElastiCache', position: { x: 400, y: 500 }, config: { memory: '1GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'tpl-e1', source: 'tpl-cdn', target: 'tpl-gw' },
      { id: 'tpl-e2', source: 'tpl-gw', target: 'tpl-api' },
      { id: 'tpl-e3', source: 'tpl-gw', target: 'tpl-sqs' },
      { id: 'tpl-e4', source: 'tpl-sqs', target: 'tpl-worker' },
      { id: 'tpl-e5', source: 'tpl-api', target: 'tpl-pg' },
      { id: 'tpl-e6', source: 'tpl-api', target: 'tpl-redis' },
    ],
  },

  // ─── CQRS + Event Sourcing ───
  {
    id: 'cqrs-event-sourcing',
    name: 'CQRS + Event Sourcing',
    description: 'Separate read/write paths with event store, projections, and materialized views',
    category: 'microservices',
    nodes: [
      { id: 'cqrs-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 30 }, config: { rateLimit: 10000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'cqrs-cmd', type: 'api-service', category: 'backend', label: 'Command Service', position: { x: 200, y: 180 }, config: { language: 'Java', replicas: 3, cpu: '500m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'cqrs-query', type: 'api-service', category: 'backend', label: 'Query Service', position: { x: 600, y: 180 }, config: { language: 'Node.js', replicas: 4, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'cqrs-eventstore', type: 'kafka', category: 'queue', label: 'Event Store (Kafka)', position: { x: 200, y: 350 }, config: { partitions: 12, replicationFactor: 3, retentionPeriod: '30d' }, status: 'healthy' },
      { id: 'cqrs-projector', type: 'worker-service', category: 'backend', label: 'Projection Worker', position: { x: 400, y: 350 }, config: { language: 'Go', replicas: 2, concurrency: 10 }, status: 'healthy' },
      { id: 'cqrs-writedb', type: 'postgresql', category: 'database', label: 'Write DB', position: { x: 100, y: 500 }, config: { storage: '100GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'cqrs-readdb', type: 'mongodb', category: 'database', label: 'Read Model DB', position: { x: 600, y: 500 }, config: { storage: '100GB', replicaSet: true, sharding: false }, status: 'healthy' },
      { id: 'cqrs-cache', type: 'redis', category: 'cache', label: 'Query Cache', position: { x: 750, y: 350 }, config: { memory: '4GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'cqrs-e1', source: 'cqrs-gw', target: 'cqrs-cmd', label: 'writes' },
      { id: 'cqrs-e2', source: 'cqrs-gw', target: 'cqrs-query', label: 'reads' },
      { id: 'cqrs-e3', source: 'cqrs-cmd', target: 'cqrs-writedb' },
      { id: 'cqrs-e4', source: 'cqrs-cmd', target: 'cqrs-eventstore' },
      { id: 'cqrs-e5', source: 'cqrs-eventstore', target: 'cqrs-projector' },
      { id: 'cqrs-e6', source: 'cqrs-projector', target: 'cqrs-readdb' },
      { id: 'cqrs-e7', source: 'cqrs-query', target: 'cqrs-readdb' },
      { id: 'cqrs-e8', source: 'cqrs-query', target: 'cqrs-cache' },
    ],
  },

  // ─── Real-Time Chat / Collaboration ───
  {
    id: 'realtime-chat',
    name: 'Real-Time Chat Platform',
    description: 'WebSocket-based messaging with presence tracking, message persistence, and push notifications',
    category: 'real-time',
    nodes: [
      { id: 'rt-lb', type: 'load-balancer', category: 'infrastructure', label: 'Load Balancer', position: { x: 400, y: 30 }, config: { algorithm: 'ip-hash', healthCheckInterval: 10, maxConnections: 50000 }, status: 'healthy' },
      { id: 'rt-ws', type: 'api-service', category: 'backend', label: 'WebSocket Gateway', position: { x: 400, y: 180 }, config: { language: 'Node.js', replicas: 5, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'rt-auth', type: 'auth-service', category: 'backend', label: 'Auth Service', position: { x: 100, y: 180 }, config: { provider: 'JWT', replicas: 2, sessionTTL: '24h' }, status: 'healthy' },
      { id: 'rt-presence', type: 'redis', category: 'cache', label: 'Presence (Redis Pub/Sub)', position: { x: 650, y: 180 }, config: { memory: '2GB', evictionPolicy: 'volatile-lru', cluster: true }, status: 'healthy' },
      { id: 'rt-broker', type: 'kafka', category: 'queue', label: 'Message Broker', position: { x: 400, y: 350 }, config: { partitions: 24, replicationFactor: 3, retentionPeriod: '7d' }, status: 'healthy' },
      { id: 'rt-persist', type: 'worker-service', category: 'backend', label: 'Persistence Worker', position: { x: 200, y: 500 }, config: { language: 'Go', replicas: 3, concurrency: 20 }, status: 'healthy' },
      { id: 'rt-notif', type: 'worker-service', category: 'backend', label: 'Push Notification Worker', position: { x: 600, y: 500 }, config: { language: 'Node.js', replicas: 2, concurrency: 10 }, status: 'healthy' },
      { id: 'rt-db', type: 'mongodb', category: 'database', label: 'Messages DB', position: { x: 200, y: 650 }, config: { storage: '500GB', replicaSet: true, sharding: true }, status: 'healthy' },
      { id: 'rt-cache', type: 'redis', category: 'cache', label: 'Recent Messages Cache', position: { x: 500, y: 650 }, config: { memory: '8GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'rt-e1', source: 'rt-lb', target: 'rt-ws' },
      { id: 'rt-e2', source: 'rt-lb', target: 'rt-auth' },
      { id: 'rt-e3', source: 'rt-ws', target: 'rt-presence' },
      { id: 'rt-e4', source: 'rt-ws', target: 'rt-broker' },
      { id: 'rt-e5', source: 'rt-broker', target: 'rt-persist' },
      { id: 'rt-e6', source: 'rt-broker', target: 'rt-notif' },
      { id: 'rt-e7', source: 'rt-persist', target: 'rt-db' },
      { id: 'rt-e8', source: 'rt-ws', target: 'rt-cache' },
    ],
  },

  // ─── E-Commerce Platform ───
  {
    id: 'ecommerce',
    name: 'E-Commerce Platform',
    description: 'Full e-commerce stack with product catalog, cart, orders, payments, and inventory management',
    category: 'e-commerce',
    nodes: [
      { id: 'ec-cdn', type: 'cdn', category: 'frontend', label: 'CDN', position: { x: 400, y: 20 }, config: { provider: 'CloudFront', cachePolicy: '1h' }, status: 'healthy' },
      { id: 'ec-web', type: 'web-app', category: 'frontend', label: 'Storefront', position: { x: 400, y: 140 }, config: { framework: 'Next.js', replicas: 4, cdn: true }, status: 'healthy' },
      { id: 'ec-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 270 }, config: { rateLimit: 20000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'ec-catalog', type: 'api-service', category: 'backend', label: 'Product Catalog', position: { x: 100, y: 400 }, config: { language: 'Node.js', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'ec-cart', type: 'api-service', category: 'backend', label: 'Cart Service', position: { x: 300, y: 400 }, config: { language: 'Node.js', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'ec-order', type: 'api-service', category: 'backend', label: 'Order Service', position: { x: 500, y: 400 }, config: { language: 'Java', replicas: 3, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'ec-payment', type: 'api-service', category: 'backend', label: 'Payment Service', position: { x: 700, y: 400 }, config: { language: 'Go', replicas: 2, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'ec-pg', type: 'postgresql', category: 'database', label: 'Orders DB', position: { x: 500, y: 570 }, config: { storage: '500GB', replication: 2, backup: true, maxConnections: 200 }, status: 'healthy' },
      { id: 'ec-mongo', type: 'mongodb', category: 'database', label: 'Product Catalog DB', position: { x: 100, y: 570 }, config: { storage: '100GB', replicaSet: true, sharding: false }, status: 'healthy' },
      { id: 'ec-redis', type: 'redis', category: 'cache', label: 'Session + Cart Cache', position: { x: 300, y: 570 }, config: { memory: '4GB', evictionPolicy: 'volatile-lru', cluster: true }, status: 'healthy' },
      { id: 'ec-queue', type: 'rabbitmq', category: 'queue', label: 'Order Events', position: { x: 700, y: 570 }, config: { queues: 10, durable: true, maxMessageSize: '1MB' }, status: 'healthy' },
      { id: 'ec-notify', type: 'worker-service', category: 'backend', label: 'Email/SMS Worker', position: { x: 700, y: 700 }, config: { language: 'Python', replicas: 2, concurrency: 10 }, status: 'healthy' },
    ],
    edges: [
      { id: 'ec-e1', source: 'ec-cdn', target: 'ec-web' },
      { id: 'ec-e2', source: 'ec-web', target: 'ec-gw' },
      { id: 'ec-e3', source: 'ec-gw', target: 'ec-catalog' },
      { id: 'ec-e4', source: 'ec-gw', target: 'ec-cart' },
      { id: 'ec-e5', source: 'ec-gw', target: 'ec-order' },
      { id: 'ec-e6', source: 'ec-gw', target: 'ec-payment' },
      { id: 'ec-e7', source: 'ec-catalog', target: 'ec-mongo' },
      { id: 'ec-e8', source: 'ec-cart', target: 'ec-redis' },
      { id: 'ec-e9', source: 'ec-order', target: 'ec-pg' },
      { id: 'ec-e10', source: 'ec-order', target: 'ec-queue' },
      { id: 'ec-e11', source: 'ec-payment', target: 'ec-pg' },
      { id: 'ec-e12', source: 'ec-queue', target: 'ec-notify' },
    ],
  },

  // ─── Data Pipeline / ETL ───
  {
    id: 'data-pipeline',
    name: 'Data Pipeline (ETL)',
    description: 'Stream ingestion with Kafka, batch/stream processing, data lake, and analytics serving layer',
    category: 'data-pipeline',
    nodes: [
      { id: 'dp-ingest', type: 'api-service', category: 'backend', label: 'Ingestion API', position: { x: 100, y: 100 }, config: { language: 'Go', replicas: 5, cpu: '1000m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'dp-kafka', type: 'kafka', category: 'queue', label: 'Kafka (Raw Events)', position: { x: 400, y: 100 }, config: { partitions: 24, replicationFactor: 3, retentionPeriod: '14d' }, status: 'healthy' },
      { id: 'dp-stream', type: 'worker-service', category: 'backend', label: 'Stream Processor', position: { x: 400, y: 270 }, config: { language: 'Java', replicas: 4, concurrency: 20 }, status: 'healthy' },
      { id: 'dp-batch', type: 'worker-service', category: 'backend', label: 'Batch ETL', position: { x: 100, y: 270 }, config: { language: 'Python', replicas: 2, concurrency: 5 }, status: 'healthy' },
      { id: 'dp-enriched', type: 'kafka', category: 'queue', label: 'Kafka (Enriched)', position: { x: 700, y: 270 }, config: { partitions: 12, replicationFactor: 3, retentionPeriod: '7d' }, status: 'healthy' },
      { id: 'dp-lake', type: 'mongodb', category: 'database', label: 'Data Lake (S3/Mongo)', position: { x: 100, y: 440 }, config: { storage: '1TB', replicaSet: true, sharding: true }, status: 'healthy' },
      { id: 'dp-warehouse', type: 'postgresql', category: 'database', label: 'Data Warehouse', position: { x: 400, y: 440 }, config: { storage: '1TB', replication: 2, backup: true, maxConnections: 200 }, status: 'healthy' },
      { id: 'dp-serving', type: 'api-service', category: 'backend', label: 'Analytics API', position: { x: 700, y: 440 }, config: { language: 'Python', replicas: 3, cpu: '1000m', memory: '2GB', autoscaling: true }, status: 'healthy' },
      { id: 'dp-cache', type: 'redis', category: 'cache', label: 'Query Cache', position: { x: 700, y: 580 }, config: { memory: '8GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'dp-e1', source: 'dp-ingest', target: 'dp-kafka' },
      { id: 'dp-e2', source: 'dp-kafka', target: 'dp-stream' },
      { id: 'dp-e3', source: 'dp-kafka', target: 'dp-batch' },
      { id: 'dp-e4', source: 'dp-stream', target: 'dp-enriched' },
      { id: 'dp-e5', source: 'dp-batch', target: 'dp-lake' },
      { id: 'dp-e6', source: 'dp-stream', target: 'dp-warehouse' },
      { id: 'dp-e7', source: 'dp-enriched', target: 'dp-serving' },
      { id: 'dp-e8', source: 'dp-serving', target: 'dp-warehouse' },
      { id: 'dp-e9', source: 'dp-serving', target: 'dp-cache' },
    ],
  },

  // ─── Multi-Region High Availability ───
  {
    id: 'multi-region-ha',
    name: 'Multi-Region HA',
    description: 'Active-active multi-region deployment with global load balancing, regional databases, and cross-region replication',
    category: 'microservices',
    nodes: [
      { id: 'ha-glb', type: 'load-balancer', category: 'infrastructure', label: 'Global Load Balancer', position: { x: 400, y: 30 }, config: { algorithm: 'weighted', healthCheckInterval: 5, maxConnections: 100000 }, status: 'healthy' },
      { id: 'ha-gw1', type: 'api-gateway', category: 'infrastructure', label: 'Region 1 Gateway', position: { x: 200, y: 170 }, config: { rateLimit: 20000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'ha-gw2', type: 'api-gateway', category: 'infrastructure', label: 'Region 2 Gateway', position: { x: 600, y: 170 }, config: { rateLimit: 20000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'ha-api1', type: 'api-service', category: 'backend', label: 'Region 1 API', position: { x: 200, y: 320 }, config: { language: 'Go', replicas: 5, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'ha-api2', type: 'api-service', category: 'backend', label: 'Region 2 API', position: { x: 600, y: 320 }, config: { language: 'Go', replicas: 5, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'ha-db1', type: 'postgresql', category: 'database', label: 'Region 1 Primary DB', position: { x: 100, y: 480 }, config: { storage: '500GB', replication: 2, backup: true, maxConnections: 200 }, status: 'healthy' },
      { id: 'ha-db2', type: 'postgresql', category: 'database', label: 'Region 2 Replica DB', position: { x: 700, y: 480 }, config: { storage: '500GB', replication: 2, backup: true, maxConnections: 200 }, status: 'healthy' },
      { id: 'ha-cache1', type: 'redis', category: 'cache', label: 'Region 1 Cache', position: { x: 300, y: 480 }, config: { memory: '4GB', evictionPolicy: 'allkeys-lru', cluster: true }, status: 'healthy' },
      { id: 'ha-cache2', type: 'redis', category: 'cache', label: 'Region 2 Cache', position: { x: 500, y: 480 }, config: { memory: '4GB', evictionPolicy: 'allkeys-lru', cluster: true }, status: 'healthy' },
      { id: 'ha-kafka', type: 'kafka', category: 'queue', label: 'Cross-Region Replication', position: { x: 400, y: 600 }, config: { partitions: 12, replicationFactor: 3, retentionPeriod: '3d' }, status: 'healthy' },
    ],
    edges: [
      { id: 'ha-e1', source: 'ha-glb', target: 'ha-gw1' },
      { id: 'ha-e2', source: 'ha-glb', target: 'ha-gw2' },
      { id: 'ha-e3', source: 'ha-gw1', target: 'ha-api1' },
      { id: 'ha-e4', source: 'ha-gw2', target: 'ha-api2' },
      { id: 'ha-e5', source: 'ha-api1', target: 'ha-db1' },
      { id: 'ha-e6', source: 'ha-api1', target: 'ha-cache1' },
      { id: 'ha-e7', source: 'ha-api2', target: 'ha-db2' },
      { id: 'ha-e8', source: 'ha-api2', target: 'ha-cache2' },
      { id: 'ha-e9', source: 'ha-db1', target: 'ha-kafka' },
      { id: 'ha-e10', source: 'ha-kafka', target: 'ha-db2' },
    ],
  },

  // ─── SaaS Multi-Tenant ───
  {
    id: 'saas-multi-tenant',
    name: 'SaaS Multi-Tenant',
    description: 'Multi-tenant SaaS platform with tenant isolation, shared services, billing, and admin dashboard',
    category: 'saas',
    nodes: [
      { id: 'saas-cdn', type: 'cdn', category: 'frontend', label: 'CDN', position: { x: 400, y: 20 }, config: { provider: 'Cloudflare', cachePolicy: '6h' }, status: 'healthy' },
      { id: 'saas-web', type: 'web-app', category: 'frontend', label: 'Tenant App', position: { x: 250, y: 150 }, config: { framework: 'React', replicas: 4, cdn: true }, status: 'healthy' },
      { id: 'saas-admin', type: 'web-app', category: 'frontend', label: 'Admin Dashboard', position: { x: 550, y: 150 }, config: { framework: 'React', replicas: 2, cdn: true }, status: 'healthy' },
      { id: 'saas-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 280 }, config: { rateLimit: 10000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'saas-auth', type: 'auth-service', category: 'backend', label: 'Auth + Tenant Router', position: { x: 150, y: 420 }, config: { provider: 'JWT', replicas: 3, sessionTTL: '24h' }, status: 'healthy' },
      { id: 'saas-api', type: 'api-service', category: 'backend', label: 'Core API', position: { x: 400, y: 420 }, config: { language: 'Node.js', replicas: 5, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'saas-billing', type: 'api-service', category: 'backend', label: 'Billing Service', position: { x: 650, y: 420 }, config: { language: 'Go', replicas: 2, cpu: '500m', memory: '512MB', autoscaling: false }, status: 'healthy' },
      { id: 'saas-db', type: 'postgresql', category: 'database', label: 'Tenant DB (Schema-per-tenant)', position: { x: 300, y: 580 }, config: { storage: '500GB', replication: 2, backup: true, maxConnections: 300 }, status: 'healthy' },
      { id: 'saas-redis', type: 'redis', category: 'cache', label: 'Session + Rate Limit Cache', position: { x: 100, y: 580 }, config: { memory: '4GB', evictionPolicy: 'volatile-lru', cluster: true }, status: 'healthy' },
      { id: 'saas-queue', type: 'sqs', category: 'queue', label: 'Job Queue', position: { x: 550, y: 580 }, config: { type: 'Standard', visibilityTimeout: 60, retentionPeriod: '7d' }, status: 'healthy' },
      { id: 'saas-worker', type: 'worker-service', category: 'backend', label: 'Background Worker', position: { x: 700, y: 580 }, config: { language: 'Python', replicas: 3, concurrency: 10 }, status: 'healthy' },
    ],
    edges: [
      { id: 'saas-e1', source: 'saas-cdn', target: 'saas-web' },
      { id: 'saas-e2', source: 'saas-cdn', target: 'saas-admin' },
      { id: 'saas-e3', source: 'saas-web', target: 'saas-gw' },
      { id: 'saas-e4', source: 'saas-admin', target: 'saas-gw' },
      { id: 'saas-e5', source: 'saas-gw', target: 'saas-auth' },
      { id: 'saas-e6', source: 'saas-gw', target: 'saas-api' },
      { id: 'saas-e7', source: 'saas-gw', target: 'saas-billing' },
      { id: 'saas-e8', source: 'saas-auth', target: 'saas-redis' },
      { id: 'saas-e9', source: 'saas-api', target: 'saas-db' },
      { id: 'saas-e10', source: 'saas-api', target: 'saas-queue' },
      { id: 'saas-e11', source: 'saas-billing', target: 'saas-db' },
      { id: 'saas-e12', source: 'saas-queue', target: 'saas-worker' },
    ],
  },

  // ─── IoT Data Processing ───
  {
    id: 'iot-platform',
    name: 'IoT Data Platform',
    description: 'High-throughput IoT ingestion with device management, stream processing, alerts, and time-series storage',
    category: 'data-pipeline',
    nodes: [
      { id: 'iot-lb', type: 'load-balancer', category: 'infrastructure', label: 'MQTT/HTTP Ingress', position: { x: 400, y: 30 }, config: { algorithm: 'least-connections', healthCheckInterval: 5, maxConnections: 100000 }, status: 'healthy' },
      { id: 'iot-ingest', type: 'api-service', category: 'backend', label: 'Device Ingestion', position: { x: 400, y: 170 }, config: { language: 'Go', replicas: 8, cpu: '500m', memory: '256MB', autoscaling: true }, status: 'healthy' },
      { id: 'iot-auth', type: 'auth-service', category: 'backend', label: 'Device Auth', position: { x: 150, y: 170 }, config: { provider: 'JWT', replicas: 2, sessionTTL: '1h' }, status: 'healthy' },
      { id: 'iot-kafka', type: 'kafka', category: 'queue', label: 'Telemetry Stream', position: { x: 400, y: 330 }, config: { partitions: 48, replicationFactor: 3, retentionPeriod: '3d' }, status: 'healthy' },
      { id: 'iot-rules', type: 'worker-service', category: 'backend', label: 'Rules Engine', position: { x: 200, y: 490 }, config: { language: 'Java', replicas: 4, concurrency: 20 }, status: 'healthy' },
      { id: 'iot-agg', type: 'worker-service', category: 'backend', label: 'Aggregator', position: { x: 600, y: 490 }, config: { language: 'Go', replicas: 3, concurrency: 15 }, status: 'healthy' },
      { id: 'iot-tsdb', type: 'postgresql', category: 'database', label: 'TimescaleDB', position: { x: 600, y: 640 }, config: { storage: '1TB', replication: 2, backup: true, maxConnections: 200 }, status: 'healthy' },
      { id: 'iot-alerts', type: 'rabbitmq', category: 'queue', label: 'Alert Queue', position: { x: 100, y: 640 }, config: { queues: 20, durable: true, maxMessageSize: '256KB' }, status: 'healthy' },
      { id: 'iot-cache', type: 'redis', category: 'cache', label: 'Device State Cache', position: { x: 650, y: 170 }, config: { memory: '8GB', evictionPolicy: 'allkeys-lru', cluster: true }, status: 'healthy' },
      { id: 'iot-api', type: 'api-service', category: 'backend', label: 'Dashboard API', position: { x: 400, y: 640 }, config: { language: 'Node.js', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
    ],
    edges: [
      { id: 'iot-e1', source: 'iot-lb', target: 'iot-ingest' },
      { id: 'iot-e2', source: 'iot-lb', target: 'iot-auth' },
      { id: 'iot-e3', source: 'iot-ingest', target: 'iot-kafka' },
      { id: 'iot-e4', source: 'iot-ingest', target: 'iot-cache' },
      { id: 'iot-e5', source: 'iot-kafka', target: 'iot-rules' },
      { id: 'iot-e6', source: 'iot-kafka', target: 'iot-agg' },
      { id: 'iot-e7', source: 'iot-rules', target: 'iot-alerts' },
      { id: 'iot-e8', source: 'iot-agg', target: 'iot-tsdb' },
      { id: 'iot-e9', source: 'iot-api', target: 'iot-tsdb' },
      { id: 'iot-e10', source: 'iot-api', target: 'iot-cache' },
    ],
  },

  // ─── API-First Platform (BFF Pattern) ───
  {
    id: 'bff-pattern',
    name: 'Backend-for-Frontend (BFF)',
    description: 'Separate BFF layers for web, mobile, and third-party clients, each optimized for their consumer',
    category: 'microservices',
    nodes: [
      { id: 'bff-web', type: 'web-app', category: 'frontend', label: 'Web App', position: { x: 100, y: 30 }, config: { framework: 'React', replicas: 3, cdn: true }, status: 'healthy' },
      { id: 'bff-mobile', type: 'mobile-api', category: 'frontend', label: 'Mobile App', position: { x: 400, y: 30 }, config: { protocol: 'GraphQL', rateLimit: 5000 }, status: 'healthy' },
      { id: 'bff-partner', type: 'gateway', category: 'backend', label: 'Partner API', position: { x: 700, y: 30 }, config: { type: 'REST', rateLimit: 1000, timeout: '30s' }, status: 'healthy' },
      { id: 'bff-webgw', type: 'api-service', category: 'backend', label: 'Web BFF', position: { x: 100, y: 200 }, config: { language: 'Node.js', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'bff-mobilegw', type: 'api-service', category: 'backend', label: 'Mobile BFF', position: { x: 400, y: 200 }, config: { language: 'Node.js', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'bff-partnergw', type: 'api-service', category: 'backend', label: 'Partner BFF', position: { x: 700, y: 200 }, config: { language: 'Go', replicas: 2, cpu: '500m', memory: '256MB', autoscaling: true }, status: 'healthy' },
      { id: 'bff-user', type: 'api-service', category: 'backend', label: 'User Service', position: { x: 200, y: 380 }, config: { language: 'Java', replicas: 3, cpu: '500m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'bff-product', type: 'api-service', category: 'backend', label: 'Product Service', position: { x: 500, y: 380 }, config: { language: 'Go', replicas: 3, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'bff-db1', type: 'postgresql', category: 'database', label: 'Users DB', position: { x: 200, y: 530 }, config: { storage: '100GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'bff-db2', type: 'mongodb', category: 'database', label: 'Products DB', position: { x: 500, y: 530 }, config: { storage: '100GB', replicaSet: true, sharding: false }, status: 'healthy' },
      { id: 'bff-cache', type: 'redis', category: 'cache', label: 'Shared Cache', position: { x: 350, y: 530 }, config: { memory: '4GB', evictionPolicy: 'allkeys-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'bff-e1', source: 'bff-web', target: 'bff-webgw' },
      { id: 'bff-e2', source: 'bff-mobile', target: 'bff-mobilegw' },
      { id: 'bff-e3', source: 'bff-partner', target: 'bff-partnergw' },
      { id: 'bff-e4', source: 'bff-webgw', target: 'bff-user' },
      { id: 'bff-e5', source: 'bff-webgw', target: 'bff-product' },
      { id: 'bff-e6', source: 'bff-mobilegw', target: 'bff-user' },
      { id: 'bff-e7', source: 'bff-mobilegw', target: 'bff-product' },
      { id: 'bff-e8', source: 'bff-partnergw', target: 'bff-product' },
      { id: 'bff-e9', source: 'bff-user', target: 'bff-db1' },
      { id: 'bff-e10', source: 'bff-product', target: 'bff-db2' },
      { id: 'bff-e11', source: 'bff-user', target: 'bff-cache' },
      { id: 'bff-e12', source: 'bff-product', target: 'bff-cache' },
    ],
  },

  // ─── Saga / Distributed Transaction ───
  {
    id: 'saga-pattern',
    name: 'Saga (Distributed Transactions)',
    description: 'Choreography-based saga pattern for distributed transactions across order, payment, inventory, and shipping',
    category: 'microservices',
    nodes: [
      { id: 'saga-gw', type: 'api-gateway', category: 'infrastructure', label: 'API Gateway', position: { x: 400, y: 30 }, config: { rateLimit: 10000, authentication: true, logging: true }, status: 'healthy' },
      { id: 'saga-order', type: 'api-service', category: 'backend', label: 'Order Service', position: { x: 400, y: 170 }, config: { language: 'Java', replicas: 3, cpu: '1000m', memory: '1GB', autoscaling: true }, status: 'healthy' },
      { id: 'saga-bus', type: 'kafka', category: 'queue', label: 'Event Bus', position: { x: 400, y: 330 }, config: { partitions: 12, replicationFactor: 3, retentionPeriod: '14d' }, status: 'healthy' },
      { id: 'saga-payment', type: 'api-service', category: 'backend', label: 'Payment Service', position: { x: 150, y: 480 }, config: { language: 'Go', replicas: 2, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'saga-inventory', type: 'api-service', category: 'backend', label: 'Inventory Service', position: { x: 400, y: 480 }, config: { language: 'Node.js', replicas: 2, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'saga-shipping', type: 'api-service', category: 'backend', label: 'Shipping Service', position: { x: 650, y: 480 }, config: { language: 'Python', replicas: 2, cpu: '500m', memory: '512MB', autoscaling: true }, status: 'healthy' },
      { id: 'saga-db1', type: 'postgresql', category: 'database', label: 'Orders DB', position: { x: 400, y: 640 }, config: { storage: '100GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'saga-db2', type: 'postgresql', category: 'database', label: 'Payments DB', position: { x: 150, y: 640 }, config: { storage: '50GB', replication: 1, backup: true, maxConnections: 100 }, status: 'healthy' },
      { id: 'saga-db3', type: 'mysql', category: 'database', label: 'Inventory DB', position: { x: 400, y: 640 }, config: { storage: '50GB', replication: 1, backup: true, maxConnections: 150 }, status: 'healthy' },
      { id: 'saga-redis', type: 'redis', category: 'cache', label: 'Saga State Cache', position: { x: 650, y: 640 }, config: { memory: '2GB', evictionPolicy: 'volatile-lru', cluster: false }, status: 'healthy' },
    ],
    edges: [
      { id: 'saga-e1', source: 'saga-gw', target: 'saga-order' },
      { id: 'saga-e2', source: 'saga-order', target: 'saga-bus', label: 'OrderCreated' },
      { id: 'saga-e3', source: 'saga-bus', target: 'saga-payment', label: 'PaymentRequested' },
      { id: 'saga-e4', source: 'saga-bus', target: 'saga-inventory', label: 'ReserveStock' },
      { id: 'saga-e5', source: 'saga-bus', target: 'saga-shipping', label: 'ShipOrder' },
      { id: 'saga-e6', source: 'saga-payment', target: 'saga-bus', label: 'PaymentCompleted' },
      { id: 'saga-e7', source: 'saga-payment', target: 'saga-db2' },
      { id: 'saga-e8', source: 'saga-inventory', target: 'saga-db3' },
      { id: 'saga-e9', source: 'saga-order', target: 'saga-db1' },
      { id: 'saga-e10', source: 'saga-order', target: 'saga-redis' },
    ],
  },
];
