import type { Architecture, ArchitectureNode } from '@systemtwin/shared';

export function generateTerraform(architecture: Architecture): string {
  const blocks: string[] = [];

  blocks.push(`# Generated by SystemTwin`);
  blocks.push(`# Terraform configuration for: ${architecture.name}`);
  blocks.push('');
  blocks.push(`terraform {`);
  blocks.push(`  required_providers {`);
  blocks.push(`    aws = {`);
  blocks.push(`      source  = "hashicorp/aws"`);
  blocks.push(`      version = "~> 5.0"`);
  blocks.push(`    }`);
  blocks.push(`  }`);
  blocks.push(`}`);
  blocks.push('');
  blocks.push(`provider "aws" {`);
  blocks.push(`  region = "us-east-1"`);
  blocks.push(`}`);
  blocks.push('');

  // VPC
  blocks.push(`resource "aws_vpc" "main" {`);
  blocks.push(`  cidr_block           = "10.0.0.0/16"`);
  blocks.push(`  enable_dns_hostnames = true`);
  blocks.push(`  tags = { Name = "${architecture.name}-vpc" }`);
  blocks.push(`}`);
  blocks.push('');

  for (const node of architecture.nodes) {
    blocks.push(generateResource(node));
    blocks.push('');
  }

  return blocks.join('\n');
}

function generateResource(node: ArchitectureNode): string {
  const name = node.id.replace(/[^a-z0-9_]/gi, '_').toLowerCase();

  switch (node.category) {
    case 'database':
      return generateDBResource(name, node);
    case 'cache':
      return generateCacheResource(name, node);
    case 'queue':
      return generateQueueResource(name, node);
    case 'infrastructure':
      return generateInfraResource(name, node);
    default:
      return generateECSResource(name, node);
  }
}

function generateECSResource(name: string, node: ArchitectureNode): string {
  const replicas = (node.config.replicas as number) || 1;
  const cpu = parseCPU(node.config.cpu as string);
  const memory = parseMemory(node.config.memory as string);

  return [
    `resource "aws_ecs_service" "${name}" {`,
    `  name            = "${name}"`,
    `  cluster         = aws_ecs_cluster.main.id`,
    `  task_definition = aws_ecs_task_definition.${name}.arn`,
    `  desired_count   = ${replicas}`,
    `  launch_type     = "FARGATE"`,
    `}`,
    ``,
    `resource "aws_ecs_task_definition" "${name}" {`,
    `  family                   = "${name}"`,
    `  requires_compatibilities = ["FARGATE"]`,
    `  network_mode             = "awsvpc"`,
    `  cpu                      = ${cpu}`,
    `  memory                   = ${memory}`,
    `  container_definitions    = jsonencode([{`,
    `    name  = "${name}"`,
    `    image = "${name}:latest"`,
    `    portMappings = [{ containerPort = 3000 }]`,
    `  }])`,
    `}`,
  ].join('\n');
}

function generateDBResource(name: string, node: ArchitectureNode): string {
  const engine = node.type === 'postgresql' ? 'postgres' : node.type === 'mongodb' ? 'docdb' : 'mysql';
  const storage = parseInt((node.config.storage as string) || '100') || 100;

  if (node.type === 'mongodb') {
    return [
      `resource "aws_docdb_cluster" "${name}" {`,
      `  cluster_identifier = "${name}"`,
      `  engine             = "docdb"`,
      `  master_username    = "admin"`,
      `  master_password    = "changeme123"`,
      `  backup_retention_period = ${node.config.backup ? 7 : 0}`,
      `}`,
    ].join('\n');
  }

  return [
    `resource "aws_db_instance" "${name}" {`,
    `  identifier        = "${name}"`,
    `  engine            = "${engine}"`,
    `  instance_class    = "db.t3.medium"`,
    `  allocated_storage = ${storage}`,
    `  username          = "admin"`,
    `  password          = "changeme123"`,
    `  multi_az          = ${(node.config.replication as number) > 0}`,
    `  backup_retention_period = ${node.config.backup ? 7 : 0}`,
    `}`,
  ].join('\n');
}

function generateCacheResource(name: string, node: ArchitectureNode): string {
  const engine = node.type === 'redis' ? 'redis' : 'memcached';
  return [
    `resource "aws_elasticache_cluster" "${name}" {`,
    `  cluster_id      = "${name}"`,
    `  engine          = "${engine}"`,
    `  node_type       = "cache.t3.medium"`,
    `  num_cache_nodes = 1`,
    `  port            = ${engine === 'redis' ? 6379 : 11211}`,
    `}`,
  ].join('\n');
}

function generateQueueResource(name: string, node: ArchitectureNode): string {
  if (node.type === 'sqs') {
    return [
      `resource "aws_sqs_queue" "${name}" {`,
      `  name                       = "${name}"`,
      `  visibility_timeout_seconds = ${node.config.visibilityTimeout || 30}`,
      `  message_retention_seconds  = ${parseRetention(node.config.retentionPeriod as string)}`,
      `  fifo_queue                 = ${node.config.type === 'FIFO'}`,
      `}`,
    ].join('\n');
  }

  if (node.type === 'kafka') {
    return [
      `resource "aws_msk_cluster" "${name}" {`,
      `  cluster_name           = "${name}"`,
      `  kafka_version          = "3.5.1"`,
      `  number_of_broker_nodes = 3`,
      `  broker_node_group_info {`,
      `    instance_type = "kafka.m5.large"`,
      `    storage_info {`,
      `      ebs_storage_info {`,
      `        volume_size = 100`,
      `      }`,
      `    }`,
      `    client_subnets  = []`,
      `    security_groups = []`,
      `  }`,
      `}`,
    ].join('\n');
  }

  return [
    `resource "aws_mq_broker" "${name}" {`,
    `  broker_name = "${name}"`,
    `  engine_type = "RabbitMQ"`,
    `  engine_version = "3.11"`,
    `  host_instance_type = "mq.m5.large"`,
    `  user {`,
    `    username = "admin"`,
    `    password = "changeme123"`,
    `  }`,
    `}`,
  ].join('\n');
}

function generateInfraResource(name: string, node: ArchitectureNode): string {
  if (node.type === 'load-balancer') {
    return [
      `resource "aws_lb" "${name}" {`,
      `  name               = "${name}"`,
      `  internal           = false`,
      `  load_balancer_type = "application"`,
      `  subnets            = []`,
      `}`,
    ].join('\n');
  }

  return [
    `resource "aws_apigatewayv2_api" "${name}" {`,
    `  name          = "${name}"`,
    `  protocol_type = "HTTP"`,
    `}`,
  ].join('\n');
}

function parseCPU(cpu?: string): number {
  if (!cpu) return 256;
  const num = parseInt(cpu);
  if (num >= 2000) return 1024;
  if (num >= 1000) return 512;
  return 256;
}

function parseMemory(mem?: string): number {
  if (!mem) return 512;
  if (mem.includes('GB') || mem.includes('Gi')) return parseInt(mem) * 1024;
  return parseInt(mem) || 512;
}

function parseRetention(ret?: string): number {
  if (!ret) return 345600;
  const days = parseInt(ret) || 4;
  return days * 86400;
}
