import type { Architecture, ArchitectureNode } from '@systemtwin/shared';

export function generateDocumentation(architecture: Architecture): string {
  const { nodes, edges, name } = architecture;
  const lines: string[] = [];

  // Title
  lines.push(`# ${name}`);
  lines.push('');
  lines.push(`> Auto-generated architecture documentation by SystemTwin`);
  lines.push(`> Generated: ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(`This architecture consists of **${nodes.length} components** connected by **${edges.length} data flows**.`);
  lines.push('');

  // Component summary by category
  const categories = ['frontend', 'backend', 'database', 'cache', 'queue', 'infrastructure'];
  const catLabels: Record<string, string> = { frontend: 'Frontend', backend: 'Backend Services', database: 'Databases', cache: 'Caches', queue: 'Message Queues', infrastructure: 'Infrastructure' };

  lines.push('### Component Summary');
  lines.push('');
  lines.push('| Category | Count | Components |');
  lines.push('|----------|-------|------------|');
  for (const cat of categories) {
    const catNodes = nodes.filter(n => n.category === cat);
    if (catNodes.length > 0) {
      lines.push(`| ${catLabels[cat] || cat} | ${catNodes.length} | ${catNodes.map(n => n.label).join(', ')} |`);
    }
  }
  lines.push('');

  // Detailed component docs
  lines.push('## Components');
  lines.push('');

  for (const cat of categories) {
    const catNodes = nodes.filter(n => n.category === cat);
    if (catNodes.length === 0) continue;

    lines.push(`### ${catLabels[cat] || cat}`);
    lines.push('');

    for (const node of catNodes) {
      lines.push(`#### ${node.label}`);
      lines.push('');
      lines.push(`- **Type:** \`${node.type}\``);
      lines.push(`- **Category:** ${node.category}`);

      // Config details
      const configEntries = Object.entries(node.config).filter(([, v]) => v !== undefined && v !== null);
      if (configEntries.length > 0) {
        lines.push(`- **Configuration:**`);
        for (const [key, value] of configEntries) {
          lines.push(`  - ${key}: \`${value}\``);
        }
      }

      // Dependencies (outgoing edges)
      const deps = edges.filter(e => e.source === node.id);
      if (deps.length > 0) {
        lines.push(`- **Depends on:** ${deps.map(e => {
          const target = nodes.find(n => n.id === e.target);
          return target?.label || e.target;
        }).join(', ')}`);
      }

      // Dependents (incoming edges)
      const dependents = edges.filter(e => e.target === node.id);
      if (dependents.length > 0) {
        lines.push(`- **Used by:** ${dependents.map(e => {
          const source = nodes.find(n => n.id === e.source);
          return source?.label || e.source;
        }).join(', ')}`);
      }

      lines.push('');
    }
  }

  // Data Flow
  lines.push('## Data Flow');
  lines.push('');
  if (edges.length > 0) {
    lines.push('| Source | Target | Protocol |');
    lines.push('|--------|--------|----------|');
    for (const edge of edges) {
      const source = nodes.find(n => n.id === edge.source);
      const target = nodes.find(n => n.id === edge.target);
      lines.push(`| ${source?.label || edge.source} | ${target?.label || edge.target} | ${edge.protocol || edge.label || '-'} |`);
    }
  } else {
    lines.push('No data flows defined.');
  }
  lines.push('');

  // Entry points
  const entryNodes = nodes.filter(n => {
    const incoming = edges.filter(e => e.target === n.id);
    return incoming.length === 0;
  });
  if (entryNodes.length > 0) {
    lines.push('## Entry Points');
    lines.push('');
    lines.push('The following components are entry points (no incoming connections):');
    lines.push('');
    entryNodes.forEach(n => lines.push(`- **${n.label}** (\`${n.type}\`)`));
    lines.push('');
  }

  // Single points of failure
  const spofs = nodes.filter(n => {
    const outgoing = edges.filter(e => e.source === n.id).length;
    const incoming = edges.filter(e => e.target === n.id).length;
    return (outgoing > 0 || incoming > 0) && (!n.config.replicas || (n.config.replicas as number) <= 1) && n.category !== 'queue';
  });
  if (spofs.length > 0) {
    lines.push('## Risks');
    lines.push('');
    lines.push('### Potential Single Points of Failure');
    lines.push('');
    spofs.forEach(n => lines.push(`- **${n.label}** — ${n.config.replicas || 1} replica(s)`));
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [SystemTwin](https://systemtwin.dev)*');

  return lines.join('\n');
}
